# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts
add_newline = true

# Replace the '❯' symbol in the prompt with '➜'
[character] # The name of the module we are configuring is 'character'
success_symbol = "[➜](bold green)"
error_symbol   = "[✗](bold red)"


[directory]
truncation_length = 3
style = "bold blue"

# Disable the package module, hiding it from the prompt completely
[package]
disabled = true

[git_branch]
symbol = " "
style = "blue"

[git_status]
style = "bold yellow"
format = "[$all_status]($style) "

# -----------------
# Python
# -----------------
[python]
format = " [$version](green)"

# -----------------
# Node.js
# -----------------
[nodejs]
format = " [$version](cyan)"

[jobs]
disabled = true

[battery]
disabled = true
