# Get editor completions based on the config schema
# "$schema" = 'https://starship.rs/config-schema.json'
format = """
$directory\
$git_branch\
$git_status\
$fill\
$lua\
$rust\
$python\
$nodejs\
$bash\
$docker_context\
$jobs\
$cmd_duration\
$line_break\
$character"""


[fill]
symbol = ' '



# Replace the '❯' symbol in the prompt with '➜'
[character] # The name of the module we are configuring is 'character'
success_symbol = "[➜](bold green)"
error_symbol   = "[✗](bold red)"


[directory]
truncation_length = 3
style = "bold blue"


[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "
# Disable the package module, hiding it from the prompt completely
# [package]
# disabled = true

[git_branch]
symbol = " "
style = "blue"

[git_status]
style = "bold yellow"
format = "[$all_status]($style) "

# -----------------
# Python
# -----------------
[python]
style = "cyan"
symbol = " "
format = "[${symbol}${version}]($style)"

# -----------------
# Node.js
# -----------------
[nodejs]
format = " [$version](cyan)"

[battery]
disabled = true
