#!/bin/sh
# color codes; 
# https://hookagency.com/blog/website-color-schemes-2020/
BLANK='#00000000'
CLEAR='#ffffff22'
# DEFAULT='#00897bE6'
DEFAULT='#0049B7E6'
# TEXT='#00897bE6'
TEXT='#0049B7E6'
WRONG='#ff1d58bb'
KEYSTROKE='#00DDFFE6'
# VERIFYING='#00564dE6'
VERIFYING='#0049B7E6'

i3lock \
--insidever-color=$CLEAR     \
--ringver-color=$VERIFYING   \
\
--insidewrong-color=$CLEAR   \
--ringwrong-color=$WRONG     \
\
--inside-color=$BLANK        \
--ring-color=$DEFAULT        \
--line-color=$BLANK          \
--separator-color=$DEFAULT   \
\
--verif-color=$TEXT          \
--wrong-color=$WRONG         \
--time-color=$TEXT           \
--date-color=$TEXT           \
--layout-color=$TEXT         \
--keyhl-color=$KEYSTROKE     \
--bshl-color=$WRONG          \
\
--screen 1                   \
--blur 9                     \
--clock                      \
--indicator                  \
--time-str="%H:%M:%S"        \
--date-str="%A, %Y-%m-%d"    \
--ignore-empty-password      \ 
# --keylayout 1                \
# --image ~/Pictures/wallpapers/IronGiantRetroCyberPunk.png \
